### PR TITLE
Integrated Direct Debit (SEPA Debit)

### PR DESCRIPTION
**Pull request by stereu**

### CODE REVIEW

**Comment by tamerciaga** [comment]
How does this work? @Wouter0100 has a seperate commercial module Mollie Recurring.

**Comment by Wouter0100** [comment]
Also curious to @tamerciaga his question. We have had this before, see [here](https://github.com/0100Dev/WHMCS-Mollie/commit/034fc6e2c25cb9839073e7f3e91409d0d1510b17), but it wasn't working or was working different then users would expect. 

It required way more logic, and that's why 0100Dev released it's WHMCS Mollie Recurring gateway for this purpose.

**Comment by tamerciaga** [comment]
@stereu did you test this? I think like @Wouter0100 said, it requires more logic like revoking mandates, making initial 0,01 payment to give a mandate.

**Comment by Wouter0100** [comment]
@tamerciaga could be one-time recurring payments, but then still.. not sure how mandates are handled then, indeed. Curious if this is tested.

**Comment by stereu** [comment]
I tested this and we are using it but i see this is only working with previous mandate creation we do with customer inputted data and a self-developed plugin in whmcs. Forgot to mention this so i think this can be closed because it seems to only be working with our own plugin and not for the common.
Thx guys!

**Pull request closed without merging**
